services:
  paymently:
    build: .
    container_name: paymently
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./logs:/app/logs
    environment:
      - PAYMENT_API_BASE_URL=${PAYMENT_API_BASE_URL}
      - PAYMENT_API_ACCESS_TOKEN_PATH=${PAYMENT_API_ACCESS_TOKEN_PATH}
      - PAYMENT_API_INQUIRY_PATH=${PAYMENT_API_INQUIRY_PATH}
      - PAYMENT_API_HEALTHZ_PATH=${PAYMENT_API_HEALTHZ_PATH:-/v2/bill/healthz}
      - PAYMENT_API_CONNECT_TIMEOUT=${PAYMENT_API_CONNECT_TIMEOUT:-10s}
      - PAYMENT_API_READ_TIMEOUT=${PAYMENT_API_READ_TIMEOUT:-20s}
      - PAYMENT_CLIENT_KEY=${PAYMENT_CLIENT_KEY}
      - PAYMENT_CHANNEL_ID=${PAYMENT_CHANNEL_ID}
      - PAYMENT_PARTNER_ID=${PAYMENT_PARTNER_ID}
      - PAYMENT_EXTERNAL_ID=${PAYMENT_EXTERNAL_ID}
      - PAYMENT_SIGNATURE=${PAYMENT_SIGNATURE}
      - PAYMENT_AUTH_TIMESTAMP=${PAYMENT_AUTH_TIMESTAMP}
