server:
  port: 8081

payment:
  api:
    base-url: https://payment.uii.ac.id
    inquiry-path: /v2/bill/inquiry
    payment-path: /v2/bill/payment
    connect-timeout: 10s
    read-timeout: 20s
    # ↑ bisa di-override via env var PAYMENT_API_READ_TIMEOUT, mis: "5s", "60s"
  auth:
    bearer-token: ${PAYMENT_BEARER_TOKEN:eyJ0eXAiOiJ...}
    channel-id: BCAS
    partner-id: BCAS
    external-id: BCAS
    signature: ${PAYMENT_SIGNATURE:}

logging:
  level:
    com.uii.paymently: DEBUG
    org.apache.http: INFO